### ISSUE TITLE
Spectral library generation - Roadmap

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine#1918]
Things to add and change in the spectral library generation.
A collection of ideas.

- [ ] Export isotope pattern score

**Comment by SteffenHeu** [comment]
- [ ] export single features to the same library
- [ ] delete library entries

**Comment by Philipbear** [comment]
1. export the total number of all found ion forms at the same RT window
2. export modified cosine scores to spectra of other ion forms (within the RT window)

**Comment by Philipbear** [comment]
would be great if a detailed explanation of the score in 'Other matched compounds' can be provided.

**Comment by corinnabrungs** [comment]
- [ ] option to include/exclude RT or CCS values

**Comment by corinnabrungs** [comment]
.json format: no collision energy information during lib matching

**Comment by djb561** [comment]
Hi, is it possible to output features to a spectral library file without annotation? For context, we have laboratory generated samples with known source/origin, but containing unknown structures. We would like to match these unknowns within the lab samples to environmental samples to help us understand the sources.
