### ISSUE TITLE
Fragment formula dashboard - Roadmap

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine#2055]
### General
- [ ] Use absolute values comparator for sorting of mass differences abs and ppm: col.setComparator(Comparators.COMPARE_ABS_FLOAT);
- [ ] on startup: use existing formula from row. Currently does not work with formulas set by this dashboard - maybe no feature annotation
- [ ] on startup: calculate formulas automatically if no formula was found for row

### Formula prediction bottom

- [ ] add combined score column in formula prediction table, similar to formula prediction window: ResultsWindowController
- [ ] double click on formula row in table to select and replace the precursor formula
- [ ] Select formula --> open dialog to ask if graph should be updated?

### Fragments table
- [ ] add column to show which row has multiple formula options

### Neutral losses table
- [ ] Neutral losses: Maybe flip signal 1 and 2 this way the precursor is always signal 1 
- [ ] Label in fragmentation spectrum for delta mz, formula, ppm could be added to RangeMarker
